import { poppins } from "@/app/fonts";
import Header from "@/components/layout/header";
import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/theme/theme-provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
      <body
        className={`${poppins.className} antialiased dark:bg-background-dark text-text-dark`}
      >
        <Header />
        {children}
      </body>
      </ThemeProvider>
    </html>
  );
}
